name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JSB_PUBLIC_KEY: ${{ secrets.JSB_PUBLIC_KEY }}
      JSB_PRIVATE_KEY: ${{ secrets.JSB_PRIVATE_KEY }}

    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: pip install -e ".[dev]"

      - name: Test
        run: pytest
